name: Mike's GitHub Actions 
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸ¤“
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]
jobs:
  mike-github-actions-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Job info
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The branch name is ${{ github.ref }} and the repo is ${{ github.repository }}."
      # - name: Check out repository code
      #   uses: actions/checkout@v5
      # - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      - name: Job status
        run: echo "This job's status is ${{ job.status }}."
  node-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Repo cloned
        run: echo "The ${{ github.repository }} repo has been cloned to the runner."
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: '22.11.x'

          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          # Package manager should be pre-installed
          # Default: ''
          cache: 'npm'
      - name: Install NPM packages
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .                  # Path context for build
          file: ./Dockerfile          # Defaults to {context}/Dockerfile
          push: true
          # tags: user/app:latest
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{vars.DOCKERHUB_REPO}}:latest